FROM diplomovka_gradle AS GRADLE_STAGE

FROM openjdk:11
COPY --from=GRADLE_STAGE /diplomovka/build/libs/diplomovka-0.0.1-SNAPSHOT.jar /diplomovka/diplomovka.jar
CMD ["java","-jar","-Djava.security.egd=file:/dev/./urandom","/diplomovka/diplomovka.jar"]
