FROM gradle:jdk11 AS GRADLE_STAGE
COPY . /tmp/

RUN cd /tmp && gradle build jar -x test

FROM openjdk:11
COPY --from=GRADLE_STAGE /tmp/build/libs/diplomovka-0.0.1-SNAPSHOT.jar /diplomovka/diplomovka.jar
