spring:
  datasource:
    url: jdbc:mysql://mysql:3306/diplomovkadb
    username: myusername
    password: mypassword

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

  devtools:
    remote:
      secret: mysecret
  main:
    allow-circular-references: true
server:
  port: 8080